#!/bin/sh
# mksh
# Make new shell script executable file from template.

VERSION='1.2.1'

mksh_main() {
	trap _exit INT TERM

	e_args=16
	e_exists=17
	e_missing_app=18

	_require realpath

	scriptinv="$( basename "$0" )"
	scriptpath="$( realpath "$0" )"
	scriptname="$( basename "$scriptpath" )"
	scriptdir="$( dirname "$scriptpath" )"

	bare=0
	interpreter='/bin/sh'
	mode="$scriptinv"

	case "$mode" in
		mkx) ;;
		*) mode=mksh ;;
	esac

	while getopts bhi:vx opt
	do
		case $opt in
			b|x) bare=1 ;;
			h) mksh_help && return ;;
			i) bare=1; interpreter="$OPTARG" ;;
			v) mksh_version && return ;;
			*) _invalid_opt ;;
		esac
	done

	shift "$(( OPTIND - 1 ))"

	[ $# -lt 1 ] && mksh_help && return 16

	newscript="$1"

	shift

	if [ "$mode" = "mkx" ]
	then
		bare=1
		[ $# -gt 0 ] && interpreter="$1" && shift
	fi

	if [ $bare -eq 0 ]
	then
		mksh_template
	else
		mksh_bare
	fi

	chmod a+x "$newscript"
	_echo "$newscript"
	_exit
}

mksh_bare() {
	if [ ! -f "$newscript" ]
	then
		echo "#!$interpreter" > "$newscript"
		echo "" >> "$newscript"
	fi

	[ -f "$newscript" ] && chmod a+x "$newscript"
}

mksh_help() {
	[ "$mode" = "mkx" ] && mkx_help && return

cat <<USAGE
$scriptinv $VERSION

Usage: $scriptname [-bhvx] [-i interpreter] scriptfile

Make new shell script executable file from template.

Options:

	-b        Only write a bare script with only the shebang line, without template.
	          If output file already exists, make it executable.
	          Implied when called script is invoked as 'mkx'.

	-h        Show this help screen.

	-i        Specify interpreter in shebang line. Implies -b.

	-v        Show script name and version number.

	-x        Synonym of -b.

USAGE
}

mksh_template() {
	newscriptname="$( basename "$newscript" )"
	newscriptnamesc="$( echo "$newscriptname" | sed 's/-/_/g' )"

	if [ -f "$newscript" ]
	then
		_error "File already exists: $newscript"
		return $e_exists
	fi

	date="$( date +'%Y-%m-%d %H:%M:%S %Z' )"

	sed '1,/^__TEMPLATE__/d' "$scriptpath" | \
		sed "
			s/__SCRIPTNAME__/$newscriptname/g;
			s/__SCRIPTNAMESC__/$newscriptnamesc/g;
			s/__DATE__/$date/g;
		" \
		> "$newscript"
}

mksh_version() {
	_echo "$scriptname $VERSION"
}

mkx_help() {
cat <<USAGE
$scriptname $VERSION

Usage: $scriptinv [-hv] scriptfile [interpreter]

Make new base shell script executable file.
If the file already exists, it will make it executable.

When not specified, interpreter defaults to '/bin/sh'.

Options:

	-h        Show this help screen.
	-v        Show script name and version number.

USAGE
}

_echo() {
	echo "$@"
}

_error() {
	_echo "$@" >&2
}

_exit() {
	exit_code=$?
	exit $exit_code
}

_invalid_opt() {
	_error "Invalid option: $opt"
	_echo
	mksh_help
	exit $e_args
}

_require() {
	missing_bin=0

	for bin in "$@"
	do
		if ! which "$bin" > /dev/null 2>&1
		then
			missing_bin=1
			_error "Required: $bin"
		fi
	done

	if [ $missing_bin -ne 0 ]
	then
		_fatal $e_missing_app "One or more executables or apps are missing."
	fi
}

mksh_main "$@"
exit

__TEMPLATE__
#!/bin/sh
# __SCRIPTNAME__

VERSION='1.0.0'

__SCRIPTNAMESC___main() {
	trap _exit INT TERM

	e_args=16
	e_missing_app=17

	_require realpath

	scriptinv="$( basename "$0" )"
	scriptpath="$( realpath "$0" )"
	scriptname="$( basename "$scriptpath" )"
	scriptdir="$( dirname "$scriptpath" )"

	while getopts hv opt
	do
		case $opt in
			h) cmd=help ;;
			v) cmd=version ;;
			*) _invalid_opt ;;
		esac
	done

	shift "$(( OPTIND - 1 ))"

	[ -z "$cmd" ] && cmd="$1"
	shift

	[ -z "$cmd" ] && cmd="help"
	#[ -z "$cmd" ] && cmd="process"

	case "$cmd" in
		help|process|version) "__SCRIPTNAMESC___$cmd" "$@" ;;
		*) _invalid_cmd ;;
	esac

	_exit
}

__SCRIPTNAMESC___help() {
cat <<USAGE
$scriptname $VERSION

Usage: $scriptinv [-hv] command

Commands:

	help      Show this help screen.
	version   Show script name and version number.

Options:

	-h        Show this help screen.
	-v        Show script name and version number.

USAGE
}

__SCRIPTNAMESC___process() {
	true
}

__SCRIPTNAMESC___version() {
	_echo "$scriptname $VERSION"
}

_echo() {
	echo "$@"
}

_error() {
	_echo "$@" >&2
}

_exit() {
	exit_code=$?
	exit $exit_code
}

_fatal() {
	exit_code="$1"
	shift
	_error "$@"
	exit "$exit_code"
}

_invalid_cmd() {
	_error "Invalid command: $cmd"
	_echo
	__SCRIPTNAMESC___help
	exit $e_args
}

_invalid_opt() {
	_error "Invalid option: $opt"
	_echo
	__SCRIPTNAMESC___help
	exit $e_args
}

_require() {
	missing_bin=0

	for bin in "$@"
	do
		if ! which "$bin" > /dev/null 2>&1
		then
			missing_bin=1
			_error "Required: $bin"
		fi
	done

	if [ $missing_bin -ne 0 ]
	then
		_fatal $e_missing_app "One or more executables or apps are missing."
	fi
}

__SCRIPTNAMESC___main "$@"
