#!/bin/sh
# mkx
# Make new shell script executable file from template.

VERSION='2.1.0'

mkx_main() {
	trap _exit INT TERM

	e_args=16
	e_exists=17

	scriptpath="$( readlink -f "$0" )"
	scriptname="$( basename "$scriptpath" )"

	bare=0
	interpreter='/bin/sh'

	while getopts bhi:v opt
	do
		case $opt in
			b) bare=1 ;;
			h) mkx_help && return ;;
			i) bare=1; interpreter="$OPTARG" ;;
			v) mkx_version && return ;;
			*) _invalid_opt ;;
		esac
	done

	shift "$(( OPTIND - 1 ))"

	[ $# -lt 1 ] && mkx_help && return 16

	newscript="$1"

	shift

	if [ $bare -eq 0 ]
	then
		mkx_template
	else
		mkx_bare
	fi

	chmod a+x "$newscript"
	_echo "$newscript"
	_exit
}

mkx_bare() {
	if [ ! -f "$newscript" ]
	then
		echo "#!$interpreter" > "$newscript"
		echo "" >> "$newscript"
	fi

	[ -f "$newscript" ] && chmod a+x "$newscript"
}

mkx_help() {
cat <<USAGE
$scriptname $VERSION

USAGE: $scriptname [-bhvx] [-i interpreter] scriptfile

Make new shell script executable file from template.

OPTIONS:

	-b        Only write a bare script with only the shebang line, without template.
	          If output file already exists, make it executable.
	          Implied when called script is invoked as 'mkx'.

	-h        Show this help screen.

	-i        Specify interpreter in shebang line. Implies -b.

	-v        Show script name and version number.

USAGE
}

mkx_template() {
	newscriptname="$( basename "$newscript" )"
	newscriptnamesc="$( echo "$newscriptname" | sed 's/-/_/g' )"

	if [ -f "$newscript" ]
	then
		_error "File already exists: $newscript"
		return $e_exists
	fi

	date="$( date +'%Y-%m-%d %H:%M:%S %Z' )"

	sed '1,/^__TEMPLATE__/d' "$scriptpath" | \
		sed "
			s/__SCRIPTNAME__/$newscriptname/g;
			s/__SCRIPTNAMESC__/$newscriptnamesc/g;
			s/__DATE__/$date/g;
		" \
		> "$newscript"
}

mkx_version() {
	_echo "$scriptname $VERSION"
}

_echo() {
	echo "$@"
}

_error() {
	_echo "$@" >&2
}

_exit() {
	exit_code=$?
	exit $exit_code
}

_invalid_opt() {
	_error "Invalid option: $opt"
	_echo
	mkx_help
	exit $e_args
}

mkx_main "$@"
exit

__TEMPLATE__
#!/bin/sh
# __SCRIPTNAME__

VERSION='1.0.0'

__SCRIPTNAMESC___main() {
	trap _exit INT TERM

	e_args=16

	scriptinv="$( basename "$0" )"
	scriptpath="$( readlink -f "$0" )"
	scriptname="$( basename "$scriptpath" )"

	while getopts hv opt
	do
		case $opt in
			h) cmd=help ;;
			v) cmd=version ;;
			*) _invalid_opt ;;
		esac
	done

	shift "$(( OPTIND - 1 ))"

	[ -z "$cmd" ] && cmd="$1"
	[ $# -gt 0 ] && shift

	[ -z "$cmd" ] && cmd="help"
	#[ -z "$cmd" ] && cmd="process"

	case "$cmd" in
		help|process|version) "__SCRIPTNAMESC___$cmd" "$@" ;;
		*) _invalid_cmd ;;
	esac

	_exit
}

__SCRIPTNAMESC___help() {
cat <<USAGE
$scriptname $VERSION

USAGE: $scriptinv [<options>] <command> [<args>]

COMMANDS:

	help      Show this help screen.
	version   Show script name and version number.

OPTIONS:

	-h        Show this help screen.
	-v        Show script name and version number.

USAGE
}

__SCRIPTNAMESC___process() {
	true
}

__SCRIPTNAMESC___version() {
	_echo "$scriptname $VERSION"
}

_echo() {
	echo "$@"
}

_error() {
	_echo "$@" >&2
}

_exit() {
	exit_code=$?
	exit $exit_code
}

_fatal() {
	exit_code="$1"
	shift
	_error "$@"
	exit "$exit_code"
}

_invalid_cmd() {
	_error "Invalid command: $cmd"
	_echo
	__SCRIPTNAMESC___help
	exit $e_args
}

_invalid_opt() {
	_error "Invalid option: $opt"
	_echo
	__SCRIPTNAMESC___help
	exit $e_args
}

__SCRIPTNAMESC___main "$@"
