#!/usr/bin/env bash
# mkx
# Make new shell script executable file from template.

VERSION='3.1.2'

mkx_main() {
	trap _exit INT TERM

	E_ARGS=16
	E_EXISTS=17
	E_NO_TEMPLATE=18

	SCRIPT_PATH="$(readlink -f "$0")"
	SCRIPT_NAME="$(basename "$SCRIPT_PATH")"
	SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

	BARE=0
	INTERPRETER='/usr/bin/env bash'
	TEMPLATE_NAME='default'

	[ -z "$MKX_LIB_DIR" ] && MKX_LIB_DIR="$SCRIPT_DIR/lib"
	[ -z "$MKX_TEMPLATES_DIR" ] && MKX_TEMPLATES_DIR="$SCRIPT_DIR/templates"

	[ $# -lt 1 ] && _help && return

	while getopts bhi:lst:v opt; do
		case $opt in
		b) TEMPLATE_NAME='bare' ;;
		h) _help && return ;;
		i)
			TEMPLATE_NAME='bare'
			INTERPRETER="$OPTARG"
			;;
		s)
			TEMPLATE_NAME='bare'
			INTERPRETER="/bin/sh"
			;;
		t) TEMPLATE_NAME="$OPTARG" ;;
		v) _version && return ;;
		*) _invalid_opt ;;
		esac
	done

	shift "$((OPTIND - 1))"

	[ $# -lt 1 ] && _help && return 16

	NEW_SCRIPT="$1"

	shift

	_template

	chmod a+x "$NEW_SCRIPT"
	_echo "$NEW_SCRIPT"
	_exit
}

_find_template() {
	template_name="$1"

	for filepath in \
		"$MKX_TEMPLATES_DIR/$template_name.mustache" \
		"${XDG_CONFIG_HOME:-$HOME/.config}/mkx/templates/$template_name.mustache" \
		"$1"; do
		if [ -f "$filepath" ]; then
			echo "$filepath"
			return
		fi
	done
}

_echo() {
	echo "$@"
}

_error() {
	_echo "$@" >&2
}

_exit() {
	local status=$?
	exit "${1:-$status}"
}

_fatal() {
	exit_code="$1"
	shift
	_error "$@"
	_exit "$exit_code"
}

_help() {
	cat <<USAGE
$SCRIPT_NAME $VERSION

USAGE: $SCRIPT_NAME [-bhsvx] [-i <interpreter>] [-t <template>] <scriptfile>

Make new shell script executable file from template.

If the file exists, make it executable.

OPTIONS:

	-b        Only write a bare script with only the shebang line, without template.

	-h        Show this help screen.

	-i        Specify interpreter in shebang line. Implies -b if -t is not specified.

	-s        Use /bin/sh as interpreter, like '-i /bin/sh'.

	-t        Specify template file. If not specified, uses 'default'.

	-v        Show script name and version number.

USAGE
}

_invalid_opt() {
	_error "Invalid option: $opt"
	_help
	exit $E_ARGS
}

_template() {
	interpreter="$INTERPRETER"
	new_script_name="$(basename "$NEW_SCRIPT")"
	new_script_name_sc="$(echo "$new_script_name" | sed 's/-/_/g')"
	template_file="$(_find_template "$TEMPLATE_NAME")"

	if [ -z "$template_file" ]; then
		_fatal $E_NO_TEMPLATE "Template file not found: $TEMPLATE_NAME"
	fi

	if [ -f "$NEW_SCRIPT" ]; then
		_echo "Making file exectuable: $NEW_SCRIPT"
	fi

	date="$(date +'%Y-%m-%d %H:%M:%S %Z')"

	(
		# shellcheck source=lib/mo
		source "$MKX_LIB_DIR/mo"

		export script_name="$new_script_name"
		export script_name_sc="$new_script_name_sc"
		export date="$date"
		export mkx_version="$VERSION"

		mo "$template_file" >"$NEW_SCRIPT"
	)
}

_version() {
	_echo "$SCRIPT_NAME $VERSION"
}

mkx_main "$@"
exit
